# Generated by Django 4.2.16 on 2024-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=255)),
                ('activation_date', models.DateTimeField()),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('designation', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
